name: motion_env
dependencies:
  - python=3.6
  - pip:
    - django==2.0.7
    - djangorestframework==3.8.2
    - Markdown==2.6.11
    - django_filter==1.1.0
    - djangorestframework-simplejwt-3.2.3
